import turtle

print(dir(turtle))
# Configuración inicial
turtle.speed(3)  # Velocidad de dibujo
turtle.bgcolor("white")  # Color de fondo
turtle.pensize(3)  # Grosor de la pluma
turtle.color("red")  # Color de la pluma

# Dibujo del corazón
turtle.begin_fill()
turtle.left(140)
turtle.forward(180)
turtle.circle(-90, 200)
turtle.left(120)
turtle.circle(-90, 200)
turtle.forward(180)
turtle.end_fill()
turtle.circle(90, 100)
turtle.left(40)
turtle.color("white")
turtle.forward(30)
turtle.color("red")
turtle.left(90)

turtle.speed(10)

# E
turtle.forward(80)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(10)
turtle.right(180)
turtle.forward(10)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(30)
turtle.right(180)
turtle.forward(30)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(10)
turtle.left(180)
turtle.forward(10)
turtle.left(90)
turtle.color("white")
turtle.forward(30)
turtle.color("red")

# R
turtle.left(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(130)
turtle.forward(65)
turtle.left(50)
turtle.color("white")
turtle.forward(30)
turtle.color("red")
turtle.left(90)

# E
turtle.forward(80)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(10)
turtle.right(180)
turtle.forward(10)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(30)
turtle.right(180)
turtle.forward(30)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(10)
turtle.left(180)
turtle.forward(10)
turtle.left(90)
turtle.color("white")
turtle.forward(30)
turtle.color("red")

# S
turtle.forward(30)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(30)


# Salto
turtle.color("white")
turtle.forward(10)
turtle.right(90)
turtle.forward(180)
turtle.right(90)
turtle.forward(290)
turtle.right(90)
turtle.color("red")

# H
turtle.forward(80)
turtle.left(180)
turtle.forward(40)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(40)
turtle.left(180)
turtle.forward(80)
turtle.left(90)
turtle.color("white")
turtle.forward(30)
turtle.color("red")

# E
turtle.left(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(10)
turtle.right(180)
turtle.forward(10)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(30)
turtle.right(180)
turtle.forward(30)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(10)
turtle.left(180)
turtle.forward(10)
turtle.left(90)
turtle.color("white")
turtle.forward(30)
turtle.color("red")

# R
turtle.left(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(130)
turtle.forward(65)
turtle.left(50)
turtle.color("white")
turtle.forward(10)
turtle.color("red")

# M
turtle.left(90)
turtle.forward(80)
turtle.right(90)
turtle.right(45)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.right(135)
turtle.forward(80)
turtle.left(90)
turtle.color("white")
turtle.forward(30)
turtle.color("red")

# O
turtle.left(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(30)
turtle.right(180)
turtle.forward(30)
turtle.color("white")
turtle.forward(30)
turtle.color("red")

# S
turtle.forward(30)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(30)
turtle.color("white")
turtle.forward(10)
turtle.right(90)
turtle.forward(80)
turtle.left(90)
turtle.forward(20)
turtle.color("red")

# A
turtle.left(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(40)
turtle.right(180)
turtle.forward(40)
turtle.right(90)
turtle.forward(40)


# Esconder la pluma
turtle.hideturtle()

# Mantener la ventana abierta
turtle.done()

